### ISSUE TITLE
How to embed?

### ISSUE THREAD

**Issue by ToTheMax5** [nesbox/emulator#15]
When trying to embed NesBox in my Weebly site, I had some trouble, even after reading your instructions. Any suggestions would be a huge help.

**Comment by ToTheMax5** [comment]
Please help?

**Comment by sinbad13** [comment]
ToTheMAx5, what exactly is the problem?

**Comment by nesbox** [comment]
@ToTheMax5 hi, could you please provide page url with problem? I'll try to understand what's the problem. Thank you.

**Comment by ToTheMax5** [comment]
http://tothemax5.weebly.com
This is the site, if you want the editable site I'll give you my credentials for Weebly. I'm just trying to embed the emulator.

**Comment by nesbox** [comment]
@ToTheMax5 I found the page http://tothemax5.weebly.com/nesbox.html where you are trying to load nesbox.swf from the url http://tothemax5.weebly.com/uploads/flash/Nesbox.swf but your server returned 404 error. So, as I see, you have to point right urls to load the emulator correctly.

**Comment by ToTheMax5** [comment]
@nesbox How do I do that?

**Comment by ToTheMax5** [comment]
Does anyone know?

**Comment by ToTheMax5** [comment]
:(

**Comment by ToTheMax5** [comment]
Anybody?

**Comment by j0hnn** [comment]
Upload Nesbox.swf somewhere and where you're embedding it on that page change `'flash/Nesbox.swf'` to the full path where you've uploaded it.

**Comment by ToTheMax5** [comment]
Thanks! Will try.

**Comment by ToTheMax5** [comment]
What link should I use? Just a link to the file on the page
