### ISSUE TITLE
Cross Server Issue

### ISSUE THREAD

**Issue by vici0usx** [nesbox/emulator#19]
The player was working perfectly when I had all my files locally, www.loveroms.com/r/...
Now that I've moved my files to dl2.loveroms.com/r/... the emulator loads fine, but the roms wont load. I also get an issue with something "crossdomain.xml", not sure if this is related to your emulator?

Example:
http://www.loveroms.com/play-online/super-nintendo/2020-super-baseball/16068

**Comment by vici0usx** [comment]
Figured it out, 

http://www.adobe.com/devnet/adobe-media-server/articles/cross-domain-xml-for-streaming.html

**Comment by hsn382** [comment]
How would you explain that to integrate the website. I can not. Please help.
