### ISSUE TITLE
French Game Release plays at 60FPS/NTSC

### ISSUE THREAD

**Issue by Catarax** [nesbox/emulator#22]
Bug found on : NES/SNES/Megadrive

A french release of a game plays at 60FPS in NTSC rather than locked at a PAL framerate of 50FPS.
(Using Fraps for Windows)

You can hear it with speedy music and a gameplay way too fast.
I fixed it by locking the NTSC framerate at 50 FPS but i think it could run better as a PAL game properly detected.

Games with this kind of issue :
NES (Dragon Ball: Le Secret du Dragon)
SNES (Dragon Ball Z : La Légende Saien)
Megadrive (Dragon Ball Z: L'Appel du Destin)

**Comment by nesbox** [comment]
@Catarax I cannot autodetect PAL but there is parameter 'ntsc' (true by default). Make it false and game will start in PAL mode

**Comment by Catarax** [comment]
Many thanks for the reply!
