### ISSUE TITLE
Need Emulator to Read Zip

### ISSUE THREAD

**Issue by vici0usx** [nesbox/emulator#3]
Hi,

All of the ROMs are zipped on my website. I would like to add the functionality to read .zip files that have all the compatiable files inside. It would be very helpful.

I am happy to donate to your cause and appreciate your continual work on this project. The faster the better :+1: 

Regards,
Jacob

**Comment by nesbox** [comment]
Hi, could you please send me an example of .zip compressed rom from your website to test the issue. Thank you.

**Comment by vici0usx** [comment]
Emailed

**Comment by nesbox** [comment]
@vici0usx fixed, pls check and let me know if all is ok

**Comment by gundamkid** [comment]
Thank you @nesbox :+1:  . I need it too.

**Comment by vici0usx** [comment]
This works great! Thank you very much for the fix. Love the work and of course, more emulators would be awesome! Thanks again,
