### ISSUE TITLE
I have a problem with embedding

### ISSUE THREAD

**Issue by Sandwall** [nesbox/emulator#31]
I have a github page, and I was planning to add NESbox. It's a fork of this project. But I can't figure out how to embed it.
Here's the repo: [https://github.com/Alobex/nesbox](url)
And here is the site: [http://alobex.github.io/nesbox/](url)

**Comment by Sandwall** [comment]
And if I try a smc fie with weebly, then it says click to play the game, and whenever I hover over it, I get the fullscreen button, and the save buttons
Here is my weebly:[http://awegame1.weebly.com/nesbox.html](url)

**Comment by nesbox** [comment]
@Alobex hi, as I see you have problems with relative paths to the .swf files
On the page http://alobex.github.io/nesbox/ I caught the error "http://alobex.github.io/nesbox/flash/Nesbox.swf Failed to load resource: the server responded with a status of 404 (Not Found)". Please enter correct path here "swfobject.embedSWF('flash/Nesbox.swf', 'emulator', '640', '480', '11.2.0', 'flash/expressInstall.swf', flashvars, params, attributes);"

**Comment by Alobex** [comment]
Wait, I thought I did that, check out my index.html at my repo

**Comment by Sandwall** [comment]
Actually the correct path for me was flash/flash/Nesbox.swf and flash/flash/expressInstall.swf
Thanks!
But the weebly is still not working

**Comment by nesbox** [comment]
now your flashvars parameter is empty
it has to be like this
var flashvars = 
 {
         system : 'sega',
         url : '/roms/Flappy Bird (PD) v1.0.gen'
};

**Comment by Alobex** [comment]
How can I do that? Weebly is block based

**Comment by Alobex** [comment]
I also have another question, how can I get my favicon to work?
