### ISSUE TITLE
How do you add this to a website?

### ISSUE THREAD

**Issue by squarepear** [nesbox/emulator#34]
I am trying to make a website with a bunch of games, some of them will be games I made others will be things like Super Mario Bros. 3. I was trying to add this to my website and I got confused on how all the files are supposed to go. So could you please make an folder that just has a working game so that I can edit it for my site?

Thanks!

**Comment by nesbox** [comment]
Hi,
- just download this .zip https://github.com/nesbox/emulator/archive/master.zip
- unpack
- copy 'bin' folder to your website
- add code https://github.com/nesbox/emulator#how-to-embed-the-emulator-to-your-webpage to your html
- copy rom file to your website
- change url to your rom in the script (url : '/roms/Flappy Bird (PD) v1.0.gen')

**Comment by squarepear** [comment]
It is still not working

[http://www.mediafire.com/download/edkh6iix111wxxr/Website.zip](http://www.mediafire.com/download/edkh6iix111wxxr/Website.zip)

that is the site file stuff, The Ngame1.html is going to be Super Mario Bros 3. Why is it not working?

**Comment by dosboxonline** [comment]
Replace "system : 'sega'" - "system : 'nes'" and upload on web server. Local not work.

**Comment by hgoda90** [comment]
The flashvar code in the embed code is what system you want and where the rom file is located. So if you want a nes game and your file is located in a folder called roms, the code would look like:

var flashvars = 
                {
                    system : 'nes',
                    url : "roms/Super Mario Bros. 3.nes"
                };

The system part of the code is what system you want loaded. The url part points to the game it should load.

You might also have to change the location of the Nesbox.swf file. The code looks like:

swfobject.embedSWF('NesboxFileLocation/Nesbox.swf', 'emulator', '640', '480', '12.2.0', 'flash/expressInstall.swf', flashvars, params, attributes);

**Comment by Wrongful** [comment]
Not sure if this is the right place, but...
I'm trying to make a simple website using Notepad++, and I want to embed a nesbox emulator that played Earthbound. I uploaded the folders, and I did as instructed, yet when I click "Run in Chrome", it just displays the code as if it's regular text. I set the language to Javascript, and I have all of the bin folders, and I'm fairly sure I did everything right. Here's the link:
file:///D:/Docs/new%201.js
I'm rather new to programming, so please explain simply!

**Comment by askplove** [comment]
how copy 'bin' folder to my wordpress website?

**Comment by hgoda90** [comment]
Wrongful the link shows if it was on your computer and not on an actual link. Plus to actually use the embedded version of Nesbox you have to have the files on some sort of server, actual server or a virtual server with something like Xampp.

**Comment by ChristianNar** [comment]
**Hi, I Webpage (add Nesbox) is "Show Not Working"
[https://mega.nz/#!Us1hnQjR!wrRZ7B42cpoDsYZx3b0ZalPv-8YbHAAozsTNq3oF0Ys](url)
File site "Nesbox.html"**

**Comment by bootheidiot** [comment]
I want to upload nesbox to google sites but I don't know how anyone know how to do this?

**Comment by eviL-Lizard** [comment]
> Wrongful the link shows if it was on your computer and not on an actual link. Plus to actually use the embedded version of Nesbox you have to have the files on some sort of server, actual server or a virtual server with something like Xampp.

Please explain more please

**Comment by Laveniuk** [comment]
Do you know how I would be able to add this emulator to my website.  I am using Sitebuilder.com  Its quite a simple system but may not be able to add this.
Any thoughts?

**Comment by GuillermoCAB** [comment]
Hey bro, so i dont know how does sitebuilder.com works, so i can't say for
sure, said that, insert nesbox on your code is a easy task, i just need to
copy and paste some code snippets on your html. Most of builder sites, like
wix (i imagine sitebuilder also) have ways to insert code direct into the
website.
You probably need some experience with code and frontend but is not rocket
science, maybe a few youtube lessons and you'll be able to do it. Also
check stackoverflow forum and see if someone knows how to do it.

Muito Grato,
Guillermo de Camargo


Em ter., 28 de abr. de 2020 às 17:17, Laveniuk <notifications@github.com>
escreveu:

**Comment by Laveniuk** [comment]
There are custom HMTL sections you can put on per page.
Were you able to do it with Wix?

**Comment by Laveniuk** [comment]
I just spoke with sitebuilder.com's tech chat, and they said there is no access to the directories.  So this is probably not possible then.
