### ISSUE TITLE
base64

### ISSUE THREAD

**Issue by colt05** [nesbox/emulator#35]
Hi.
I have been testing Nesbox with loading ROMs from websites. I have successfully used code that will get a rom, convert it into base 64, and convert the base 64 into a Data URI. Unfortunately, Nesbox does not support Data URIs. Is there another way to load roms from different websites, or use the base 64 with Nesbox?
Thanks!
http://colt05.github.io/nesbox/test3

**Comment by nesbox** [comment]
Unfortunately, there is no way to load base64 roms.
But if you want to load roms from different websites you have to add crossdomain.xml policy file to them.
http://www.adobe.com/devnet/articles/crossdomain_policy_file_spec.html

**Comment by colt05** [comment]
thanks!!
do you have to use crossdomain.xml even while using a cross-origin resource sharing proxy?
i will use http://phphostcolt05.comlu.com/asFile.php?base=(insert base64 here)

**Comment by nesbox** [comment]
I think it's a bad way to use base64 in URL address, maximum length of url is ~2000 characters

**Comment by colt05** [comment]
is there another way to display it on a webpage using php? github pages does not support php so I can't use that. is there cross origin local storage (use one website to set the local storage of another website)?

**Comment by nesbox** [comment]
pls read how to use crossdomain.xml for adobe flash.
you just have to put the crossdomain.xml file on a website with roms and then load roms from website with the emulator

**Comment by colt05** [comment]
==question moved to separate issue===
