### ISSUE TITLE
Region Issue / Sega Mega Drive & Genesis

### ISSUE THREAD

**Issue by vici0usx** [nesbox/emulator#6]
I get this message when trying to Play Aladdin:
www.loveroms.com/play-online/sega-genesis/aladdin-e-/808

"Developed for use only with PAL and French Secam Mega Drive Systems"

Any idea how we can fix this?

**Comment by nesbox** [comment]
@vici0usx I think you should use region parameter with 'e' value. Like 
{
system:'sega',
url:'...',
region:'e'
}
Supported regions: u - for USA roms (default), e - for Europe roms, j - for Japanese roms

**Comment by vici0usx** [comment]
Awesome! Great feature. Thank you.

**Comment by vici0usx** [comment]
I got this implemented and tried it with various Europe ROMs, I still have the same issue. This is an example output:

 system : 'sega',
 url : 'Aladdin%20(E)%20[!].zip',
 region : 'e'

**Comment by nesbox** [comment]
Pls send me this rom, I'll try to investigate.

**Comment by vici0usx** [comment]
Here you go

-------------------------------------------------
JACOB MATHIAS
Web Developer

Rather Talk?
Call - 928.358.8628

**Comment by nesbox** [comment]
I've got the problem. Please add 'ntsc:false' parameter for all European roms.

**Comment by vici0usx** [comment]
Worked, thanks !!!

**Comment by thumbtak1** [comment]
"I've got the problem. Please add 'ntsc:false' parameter for all European roms."

How do I add this?

**Comment by qadras33** [comment]
> @vici0usx I think you should use region parameter with 'e' value. Like { system:'sega', url:'...', region:'e' } Supported regions: u - for USA roms (default), e - for Europe roms, j - for Japanese roms

Thanks!!
